### ISSUE TITLE
Unable to set_value for a Mat

### ISSUE THREAD

**Issue by azmathmoosa** [stereolabs/zed-python-api#178]
I am playing with ZED 2's depth_sensing demo.  I want to modify the point cloud based on certain criteria.  For that, I am using the set_value function but it is not working.

```python
point_cloud = sl.Mat(res.width, res.height, sl.MAT_TYPE.F32_C4, sl.MEM.CPU)
zed.retrieve_measure(point_cloud, sl.MEASURE.XYZRGBA,sl.MEM.CPU, res)
x=600
y=400
_, xyzrgba = point_cloud.get_value(x,y)
xyzrgba[2] = 0.0
print("xyzrgba", xyzrgba)
point_cloud.set_value(x,y, xyzrgba)
```
I get a `TypeError` when set_value is called.
```
xyzrgba [ 2.35197315e+01  9.14721375e+02  0.00000000e+00 -2.23503209e+38]
Traceback (most recent call last):
  File "depth_sensing.py", line 204, in <module>
    run()
  File "depth_sensing.py", line 185, in run
    point_cloud = plot_depth(pcloud=point_cloud)
  File "depth_sensing.py", line 155, in plot_depth
    point_cloud.set_value(x,y, xyzrgba)
  File "pyzed/sl.pyx", line 2886, in pyzed.sl.Mat.set_value
TypeError: an integer is required
```

My question is, 
1. How to manipulate Mat with set_value. 
2. And secondly, is there a better way to do it using numpy?  If I use get_data, I get a numpy array.  Can I manipulate this numpy array and reinit a Mat from it?

**Comment by qt-truong** [comment]
Hi @azmathmoosa,

Your piece of code is correct and there is actually a bug inside the Python API, thanks for reporting it! It will be fixed in the next release.

Unfortunately, there is no direct and optimal way to reinit an sl.Mat from a numpy array, so the best way to perform what you are trying to do is to indeed use the API function `set_value`.

Sorry for the inconvenience. Hope it helps.
